"""Domain models"""
from .requests import (
    SessionConfig,
    CommandPayload,
    ScraperRequest,
    SerperRequest,
    ActionResult,
    SessionStatus,
)
from .dsl import (
    GoToParams,
    ClickParams,
    ClickCoordinateParams,
    ScrollParams,
    TypeParams,
    PressKeyParams,
    ScreenshotParams,
    ExtractHTMLParams,
    ExtractTextParams,
    OmniClickParams,
    ExtractWithJinaParams,
    DecideNextParams,
    ActionParams,
)

__all__ = [
    "SessionConfig",
    "CommandPayload",
    "ScraperRequest",
    "SerperRequest",
    "ActionResult",
    "SessionStatus",
    "GoToParams",
    "ClickParams",
    "ClickCoordinateParams",
    "ScrollParams",
    "TypeParams",
    "PressKeyParams",
    "ScreenshotParams",
    "ExtractHTMLParams",
    "ExtractTextParams",
    "OmniClickParams",
    "ExtractWithJinaParams",
    "DecideNextParams",
    "ActionParams",
]
